# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: render_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'render_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14render_service.proto\x12\x06Render\"9\n\nImageChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\"<\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x0b\n\x03\x62ps\x18\x03 \x01(\r\"\x1e\n\tSetAvatar\x12\x11\n\tavatar_id\x18\x01 \x01(\t\"\"\n\rPlayAnimation\x12\x11\n\tanimation\x18\x01 \x01(\t\"\x1d\n\nSetEmotion\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t\"\x9b\x02\n\rRenderRequest\x12!\n\x05image\x18\x01 \x01(\x0b\x32\x12.Render.ImageChunk\x12!\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x12.Render.AudioChunk\x12\x0e\n\x06online\x18\x03 \x01(\x08\x12\r\n\x05\x61lpha\x18\x04 \x01(\x08\x12\'\n\nset_avatar\x18\x05 \x01(\x0b\x32\x11.Render.SetAvatarH\x00\x12/\n\x0eplay_animation\x18\x06 \x01(\x0b\x32\x15.Render.PlayAnimationH\x00\x12)\n\x0bset_emotion\x18\x07 \x01(\x0b\x32\x12.Render.SetEmotionH\x00\x12\x15\n\routput_format\x18\x08 \x01(\tB\t\n\x07\x63ommand\"9\n\nVideoChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r2N\n\rRenderService\x12=\n\x0cRenderStream\x12\x15.Render.RenderRequest\x1a\x12.Render.VideoChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'render_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECHUNK']._serialized_start=32
  _globals['_IMAGECHUNK']._serialized_end=89
  _globals['_AUDIOCHUNK']._serialized_start=91
  _globals['_AUDIOCHUNK']._serialized_end=151
  _globals['_SETAVATAR']._serialized_start=153
  _globals['_SETAVATAR']._serialized_end=183
  _globals['_PLAYANIMATION']._serialized_start=185
  _globals['_PLAYANIMATION']._serialized_end=219
  _globals['_SETEMOTION']._serialized_start=221
  _globals['_SETEMOTION']._serialized_end=250
  _globals['_RENDERREQUEST']._serialized_start=253
  _globals['_RENDERREQUEST']._serialized_end=536
  _globals['_VIDEOCHUNK']._serialized_start=538
  _globals['_VIDEOCHUNK']._serialized_end=595
  _globals['_RENDERSERVICE']._serialized_start=597
  _globals['_RENDERSERVICE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
