# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: render_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'render_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14render_service.proto\x12\x06Render\"9\n\nImageChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\"<\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x0b\n\x03\x62ps\x18\x03 \x01(\r\"e\n\rRenderRequest\x12!\n\x05image\x18\x01 \x01(\x0b\x32\x12.Render.ImageChunk\x12!\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x12.Render.AudioChunk\x12\x0e\n\x06online\x18\x03 \x01(\x08\"9\n\nVideoChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r2N\n\rRenderService\x12=\n\x0cRenderStream\x12\x15.Render.RenderRequest\x1a\x12.Render.VideoChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'render_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECHUNK']._serialized_start=32
  _globals['_IMAGECHUNK']._serialized_end=89
  _globals['_AUDIOCHUNK']._serialized_start=91
  _globals['_AUDIOCHUNK']._serialized_end=151
  _globals['_RENDERREQUEST']._serialized_start=153
  _globals['_RENDERREQUEST']._serialized_end=254
  _globals['_VIDEOCHUNK']._serialized_start=256
  _globals['_VIDEOCHUNK']._serialized_end=313
  _globals['_RENDERSERVICE']._serialized_start=315
  _globals['_RENDERSERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
